### ISSUE TITLE
EJERCICIO B - SISTEMA IOT - Comunicación a Internet

### ISSUE THREAD

**Issue by OscarAGazzola** [ISPC-TST-Sensores-y-Actuadores/practica-de-la-1er-semana-grupo-3#18]
Comunicacion a Internet: Satelital / WiFi / LAN / GSM - 3G - 4G / Wimax / LMDS

**Comment by OscarAGazzola** [comment]
Describo las distintas conexiones a Internet que existen y que posibilitan el IOT.

**Comment by WayarCarla** [comment]
ACTIVIDAD REALIZADA POR OSCAR
